# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-19 10:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='text',
            field=models.TextField(default=datetime.datetime(2018, 2, 19, 10, 43, 50, 349667, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
