# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-02-26 10:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_remove_book_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='pub_date',
            field=models.DateField(default=datetime.datetime(2018, 2, 26, 10, 25, 15, 199876, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
